app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: ['GET', 'HEAD']
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: ['GET', 'HEAD']